### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by scalp42** [berkshelf/ridley#208]
Hey folks,

Any idea on how to get around SSL certificates verification issues please ?

``` ruby
rid = Ridley.new(
  server_url: "https://chef-server.example.com",
  client_name: ENV['KNIFE_VALIDATION_CLIENT_NAME'],
  client_key: ENV['KNIFE_VALIDATION_CLIENT_KEY']
)
rid.node.all
```

I remember something about `SSL verify none` but thats about it.

Error I'm getting:

```
    /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/responses.rb:29:in `value': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Ridley::Errors::ConnectionFailed)
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/proxies/actor_proxy.rb:25:in `_send_'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/pool_manager.rb:41:in `_send_'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/pool_manager.rb:122:in `method_missing'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
      from (celluloid):0:in `remote procedure call'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/proxies/actor_proxy.rb:21:in `send'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/ridley-1.5.1/lib/ridley/resource.rb:132:in `raw_request'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/ridley-1.5.1/lib/ridley/resource.rb:123:in `request'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/ridley-1.5.1/lib/ridley/resource.rb:66:in `all'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
      from (celluloid):0:in `remote procedure call'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
      from /Users/scalp/.rvm/gems/ruby-1.9.3-p392@chef/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
      from ./route53_cleaning.rb:23:in `<main>'
```

Thanks in advance for any help!

**Comment by samsonkolge** [comment]
@ivey Is there a way to use verify_peer setting? In customer environment, setting this to none may not be ideal. Please advise.

**Comment by thommay** [comment]
@samsonkolge please don't comment on 4 year old tickets. For help, please use https://discourse.chef.io .
