### ISSUE TITLE
Ridley 4.4.2 doesn't work with Chef < 12.5

### ISSUE THREAD

**Issue by bbrownz** [berkshelf/ridley#336]
I started running into an issue with the 4.4.2 version of ridley that resulted in the following error

```
/var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley/chef/config.rb:2:in `require': cannot load such file -- chef-config/workstation_config_loader (LoadError)
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley/chef/config.rb:2:in `<top (required)>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley/chef.rb:6:in `require_relative'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley/chef.rb:6:in `<module:Chef>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley/chef.rb:4:in `<module:Ridley>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley/chef.rb:1:in `<top (required)>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley.rb:69:in `require_relative'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley.rb:69:in `<module:Ridley>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/ridley-4.4.2/lib/ridley.rb:15:in `<top (required)>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/berkshelf-4.0.1/lib/berkshelf.rb:7:in `require'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/berkshelf-4.0.1/lib/berkshelf.rb:7:in `<top (required)>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:1:in `require'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:1:in `<top (required)>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/berkshelf-4.0.1/bin/berks:3:in `require'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/gems/berkshelf-4.0.1/bin/berks:3:in `<top (required)>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/bin/berks:23:in `load'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/bin/berks:23:in `<main>'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/bin/ruby_executable_hooks:15:in `eval'
	from /var/lib/spork/.rvm/gems/ruby-2.1.2@pop_health_main/bin/ruby_executable_hooks:15:in `<main>'
```

It looks like 4.4.2 included a change (#333) to start using chef-config again, including `require 'chef-config/workstation_config_loader'`. However, workstation_config_loader wasn't moved into chef-config [until 12.5.0](https://github.com/chef/chef/commit/6a4f414666b3688a3dfa94b131f83235f4d2fa64#diff-bd822a94b8aff21b210a0f423916fe57). It would be worth noting in the gemspec the minimum chef-config version required.

**Comment by Chili-Man** [comment]
I am running into this issue as well

**Comment by dougalb** [comment]
I've addressed this by doing a versioned install of ridley and berkshelf.

I specifically install ridley-4.3.2 and berkshelf-4.0.1

https://github.com/awslabs/cfncluster-cookbook/blob/develop/packer_alinux.json#L82
